spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  session:
    store-type: jdbc
    spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: HRb6CbFvTFpCQxoP_dRE
#            client-secret: 62DrmJvYPn
#            redirect-uri: ${baseUrl}/${action}/oauth2/code/${registrationId} 
#            authorization-grant-type: authorization_code
#            client-name: Naver
#            scope:
#            - profile
#            - email
#            - profile_image
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response